### ISSUE TITLE
Fix branch issues immediately 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/Juetcecoursemanagementsystem#13]
Always maintain this working scheme ...
git pull origin master : pulling master branch to your working branch local repo i.e . arijit/develop

Do proper code change ...
git commit to arijit/develop 

Make a pull request always from arijit/develop to master

Repeat this rule (mentioned above) and dont push anything to any branch except arijit/devolop
@Arijit02

**Comment by ayan-biswas0412** [comment]
Now what have you done please make a proper pull request from arijit/develop to master

**Comment by ayan-biswas0412** [comment]
Done , nice work and please continue this process for everytime you push @Arijit02

**Comment by Arijit02** [comment]
Ok thanks, please close the issue.

**Comment by Arijit02** [comment]
Done....
