### ISSUE TITLE
Please Do the Staff sign in backend ASAP (Login not working)

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/Juetcecoursemanagementsystem#21]
* faculty logins will be created from admin dashboard with just two parameters (email id and Name of Faculty )
* After creation of Faculty Account a email will be sent stating that your account has been created with name : Faculty_name and userid is : email and change your password from this link...
with (same algo will be used of reset password)

* And admin accounts will be created from the phpmyadmin panel

* the login.inc.php for staff login is not working properly 

@Arijit02

**Comment by ayan-biswas0412** [comment]
Please do it , I have tried but the same thing is happening every time after clicking login a white screen appears.

**Comment by ayan-biswas0412** [comment]
![Screenshot from 2020-04-14 17-33-56](https://user-images.githubusercontent.com/52851184/79223003-2c23b600-7e76-11ea-8753-c073139ea078.png)
This is showing i mean somehow the sql error is happening everytime please look into it

**Comment by Arijit02** [comment]
[video.zip](https://github.com/ayan-biswas0412/Juetcecoursemanagementsystem/files/4475212/video.zip)
I my case it is working perfectly fine, see the attached video in the zip file. Maybe some  with your machine (a typo maybe because mysqli_stmt_prepare not working , maybe some issue with the table name)

**Comment by ayan-biswas0412** [comment]
Please see the comment in  #28

**Comment by ayan-biswas0412** [comment]
Done by @Arijit02
