### ISSUE TITLE
Manual password entry issue

### ISSUE THREAD

**Issue by Arijit02** [ayan-biswas0412/Juetcecoursemanagementsystem#28]
password of admins need to be manually hashed before entering in phpmyadmin

**Comment by ayan-biswas0412** [comment]
Please profide the table's sql file click on the table (users_staff) at phpmyadmin and export the sql and attach the file here in this issue

**Comment by Arijit02** [comment]
[users_staff.zip](https://github.com/ayan-biswas0412/Juetcecoursemanagementsystem/files/4475472/users_staff.zip)

**Comment by ayan-biswas0412** [comment]
ektu tor leg dust email kr amk ami etokkhn code e bug khuje beracchi edike dekhi tui actual table er column tar name **role** theke change kre **staff_role** kre diyechis

jar jnno oi stament_prepare ta false hcchilo barbar r error aschilo.
Ebar kaj krche thikthak

**Comment by ayan-biswas0412** [comment]
Solved by @Arijit02
