### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by Arijit02** [ayan-biswas0412/Juetcecoursemanagementsystem#33]
undefined index course_code on faculty dashboard
![Screenshot from 2020-04-15 18-36-09](https://user-images.githubusercontent.com/59946663/79340599-2696a080-7f48-11ea-8f46-158fed78a3da.png)

**Comment by ayan-biswas0412** [comment]
Haa chap khas na prevent login er problem ache ekta thik kre dicchi ekhni tui notice ta dekh age

**Comment by ayan-biswas0412** [comment]
Please see the #34 and pul that branch in your local computer and test that if it is okay then tell me in this issue and write a short report if anything more needed to do in this issue
