### ISSUE TITLE
There remains a gap of navbar on both the side in admin dashboard

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/Juetcecoursemanagementsystem#40]
![Screenshot from 2020-04-17 15-14-30](https://user-images.githubusercontent.com/52851184/79556177-57004b00-80be-11ea-9e6b-516c0aee8893.png)
Please try to fix this . 
#39 
pull ayan/develop2 branch in a new local branch and if fixed please make a pull request to the ayan/develop2 branch

**Comment by Arijit02** [comment]
In admin-sem_info.php add "style = 'margin: -1.5%' " in body tag. Hopefully it will help.

**Comment by ayan-biswas0412** [comment]
ISSUED NOTICE AND ARCHIVED NOTICE PART IS NOT THERE

**Comment by ayan-biswas0412** [comment]
Do a archived notice section that containes all the notices with status archived . Until then i will try to do a issued notice section.

**Comment by ayan-biswas0412** [comment]
Done by @ayan-biswas0412
