### ISSUE TITLE
Sign up is not working properly.

### ISSUE THREAD

**Issue by arindammajee** [ayan-biswas0412/Juetcecoursemanagementsystem#58]
- ### **[Screencast** from Saturday 18 April 2020 11:22:07  IST.zip](https://github.com/ayan-biswas0412/Juetcecoursemanagementsystem/files/4497334/Screencast.from.Saturday.18.April.2020.11.22.07.IST.zip)

Watch the video properly. Look that in the table 'student_userdata' there is the roll number 001910701005 but not in the table 'users'. When I click on the sign up button and put the roll number 001910701005, it shows me that the roll number is allready registered.

**Comment by ayan-biswas0412** [comment]
All thing is Right and inline ...

upadate the reg_status = "N" in case of SHREYA BISWAS this will work .

**Comment by ayan-biswas0412** [comment]
If still the issue is not solved please open another issue, and please review and test thoroughly the master branch from my repository and add bug reports here in the issue (one issue for one bug).
Thank you for reviewing
